set_property SRC_FILE_INFO {cfile:X:/GIT/litex-boards/litex_boards/partner/targets/soc_basesoc_te0725/gateware/top.xdc rfile:../../../top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M18 [get_ports serial_tx]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L18 [get_ports serial_rx]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC V10 [get_ports cpu_reset]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC P17 [get_ports clk100]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L13 [get_ports spiflash_4x_cs_n]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K17 [get_ports spiflash_4x_dq[0]]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K18 [get_ports spiflash_4x_dq[1]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC L14 [get_ports spiflash_4x_dq[2]]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M14 [get_ports spiflash_4x_dq[3]]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A13 [get_ports hyperram_clk]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A14 [get_ports hyperram_clk_n]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J17 [get_ports hyperram_rstn]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E17 [get_ports hyperram_dq[0]]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B17 [get_ports hyperram_dq[1]]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F18 [get_ports hyperram_dq[2]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC F16 [get_ports hyperram_dq[3]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC G17 [get_ports hyperram_dq[4]]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D18 [get_ports hyperram_dq[5]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC B18 [get_ports hyperram_dq[6]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC A16 [get_ports hyperram_dq[7]]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC D17 [get_ports hyperram_cs0]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC E18 [get_ports hyperram_rwds]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC M16 [get_ports user_led0]
